[package]
authors = ["Yuanchao Sun <yuanchao.sun@gmail.com>"]
edition = '2018'
name = 'ibc-demo'
version = "0.1.0"

[profile.release]
panic = 'unwind'

[workspace]
members = [
    "ibc-node",
    "relayer",
]
