[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-template'
version = '2.0.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = '1.0.0' }

[dependencies.frame-support]
default-features = false
version = '2.0.0'
path = "../../../substrate/frame/support"

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0'
path = "../../../substrate/frame/system"

[dependencies.sp-core]
default-features = false
version = '2.0.0'
path = "../../../substrate/primitives/core"

[dev-dependencies.sp-io]
default-features = false
version = '2.0.0'
path = "../../../substrate/primitives/io"

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0'
path = "../../../substrate/primitives/runtime"

[dependencies.ibc]
default-features = false
package = 'pallet-ibc'
path = "../../frame/ibc"

[dependencies.sp-std]
default-features = false
path = "../../../substrate/primitives/std"

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
    'system/std'
]
