[package]
name = "relayer"
version = "0.1.0"
authors = ["Yuanchao Sun <yuanchao.sun@gmail.com>"]
edition = "2018"

[[bin]]
name = 'relayer'
path = 'src/main.rs'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = '0.1'
hyper = "0.12"
jsonrpc-core-client = { version = "12.0.0", features = ["http", "ws"] }
env_logger = "0.6"
hex = "0.3"
hex-literal = "0.2"

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ibc-node-runtime]
path = '../ibc-node/runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'

[dependencies.rpc]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-rpc'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'

[dependencies.system]
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'

[dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'node-primitives'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-keyring'
rev = '49db9e370e1a7aa490e1fb8749545d9781432a0d'
