[package]
name = "relayer"
version = "0.1.0"
authors = ["Yuanchao Sun <yuanchao.sun@gmail.com>"]
edition = "2018"

[[bin]]
name = 'relayer'
path = 'src/main.rs'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = '0.1'
hyper = "0.12"
jsonrpc-core-client = { version = "12.0.0", features = ["http", "ws"] }
hex = "0.3"
clap = { version = "~2.32", features = ["yaml"] }
tokio = "0.1"
env_logger = "0.6"
substrate-subxt = { git="https://github.com/en/substrate-subxt.git", branch="ibc-demo" }

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.ibc-node-runtime]
path = '../ibc-node/runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '37558193cd3b8db50ad4fe5a1071bf324358ac53'

[dependencies.rpc]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-rpc'
rev = '37558193cd3b8db50ad4fe5a1071bf324358ac53'

[dependencies.system]
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '37558193cd3b8db50ad4fe5a1071bf324358ac53'

[dependencies.node-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'node-primitives'
rev = '37558193cd3b8db50ad4fe5a1071bf324358ac53'

[dependencies.keyring]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-keyring'
rev = '37558193cd3b8db50ad4fe5a1071bf324358ac53'
