[package]
name = "cli"
version = "0.1.0"
authors = ["Yuanchao Sun <ys@cdot.network>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
hex = "0.4.0"
rand = "0.7.2"
tokio = { version = "0.2", features = ["full"] }
url = "1.7"
futures = { version = "0.3.1", features = ["compat"] }
substrate-subxt = { path = "../../substrate-subxt" }
tokio-compat = { package = "tokio-compat", version = "0.1.0" }
calls = { path = "../calls" }
sp-core = { path = "../../substrate/primitives/core" }
sp-keyring = { path = "../../substrate/primitives/keyring" }
node-runtime = { path = "../runtime", package = "node-template-runtime" }
